spring.application.name=driving-test

# Database
spring.datasource.url=jdbc:postgresql://yoyo-buck-25719.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/app/root.crt
spring.datasource.username=annie
spring.datasource.password=pmyligxuGR_sNG7on4Ov5Q
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
spring.jpa.properties.hibernate.connection.CharSet=utf-8
spring.jpa.properties.hibernate.connection.useUnicode=true

# SQL Init (disable for production)
spring.sql.init.mode=never

# HTTP Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JWT config
jwt.secret=dHJhbnNmb3JtZWRTZWNyZXRLZXlGb3JEcml2aW5nVGVzdEFwcGxpY2F0aW9uMjAyNg==
jwt.expiration-ms=86400000

# Image base URL
app.image-base-url=/images/signs/

# Server port
server.port=${PORT:8080}

# Other
spring.jpa.open-in-view=false
