spring.application.name=driving-test

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/provx_driving_theory
spring.datasource.username=postgres
spring.datasource.password=Annie0005@!@!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
spring.jpa.properties.hibernate.connection.CharSet=utf-8
spring.jpa.properties.hibernate.connection.useUnicode=true

# HTTP Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Tell Spring Boot to run schema.sql then data.sql on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.encoding=UTF-8
spring.sql.init.continue-on-error=false
spring.jpa.open-in-view=false
# JWT config
jwt.secret=dHJhbnNmb3JtZWRTZWNyZXRLZXlGb3JEcml2aW5nVGVzdEFwcGxpY2F0aW9uMjAyNg==

# Image base URL
app.image-base-url=http://localhost:8081/images/signs/
jwt.expiration-ms=86400000

# Image serving base URL
app.image-base-url=/images/signs/

# Server port
server.port=${PORT:8081}
